language: go
sudo: required

gobuild_args: "-tags integration"
go:
  - "1.11rc1"

services:
  - docker

before_install:
  - docker pull dwmkerr/dynamodb
  - docker run -it -p 8000:8000 dwmkerr/dynamodb -sharedDb -inMemory
  - docker ps

install: true

notifications:
  email: false
