language: go
sudo: required

env:
  global:
    - AWS_ACCESS_KEY_ID="foo"
    - AWS_SECRET_ACCESS_KEY="bar"
    - AWS_DEFAULT_REGION="us-west-2"
    - DDBMAP_INTEG_ENDPOINT="http://localhost:8000"
    - DDBMAP_INTEG_DEBUG=1

gobuild_args: "-tags integration"
go:
  - "1.11rc1"

services:
  - docker

before_install:
  - docker pull dwmkerr/dynamodb
  - docker run -d -p 8000:8000 dwmkerr/dynamodb -sharedDb -inMemory
  - docker ps -a

install: true

notifications:
  email: false
