language: go
sudo: required

env:
  global:
    - AWS_ACCESS_KEY_ID="foo"
    - AWS_SECRET_ACCESS_KEY="bar"
    - AWS_DEFAULT_REGION="us-west-2"
    - DDBMAP_INTEG_ENDPOINT="http://localhost:8000"
    - DDBMAP_INTEG_DEBUG=1
    - GO111MODULE=on

gobuild_args: "-v -tags integration"
go:
  - "1.12"

services:
  - docker

before_install:
  - docker pull amazon/dynamodb-local
  - docker run -d -p 8000:8000 amazon/dynamodb-local
  - docker ps -a
  - go get -u

install: true

notifications:
  email: false
